import { createAddWritingPromptTool } from './add_writing_prompt';
import type { OrchestratorContext } from '../types';

jest.mock('../../memory/writing-prompts', () => ({
  autoGenerateAndSavePrompt: jest.fn(),
}));
import { autoGenerateAndSavePrompt } from '../../memory/writing-prompts';

function makeDb(overrides: Partial<Record<string, unknown>> = {}) {
  return {
    apWritingPrompt: {
      create: jest.fn().mockResolvedValue({ id: 'p-created' }),
      findFirst: jest.fn().mockResolvedValue({ id: 'p-ai', content: 'AI content', source: 'AI' }),
      update: jest.fn().mockResolvedValue({}),
      ...overrides,
    },
  };
}

function makeCtx(db: unknown = makeDb()): OrchestratorContext {
  return {
    org: { id: 'org-1' } as any,
    user: {} as any,
    db: db as any,
    llm: { model: {} as any, complete: jest.fn() } as any,
    emit: jest.fn(),
    now: new Date('2026-05-01T12:00:00Z'),
    timezone: 'UTC',
    logger: { info: jest.fn(), warn: jest.fn(), error: jest.fn() } as any,
  };
}

describe('add_writing_prompt', () => {
  const tool = createAddWritingPromptTool();

  beforeEach(() => jest.clearAllMocks());

  it('has correct name', () => {
    expect(tool.name).toBe('add_writing_prompt');
  });

  it('saves user-supplied content as USER source', async () => {
    const db = makeDb();
    const ctx = makeCtx(db);
    const result = await tool.handler(ctx, { content: 'Always use short sentences.' });
    expect((db as any).apWritingPrompt.create).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({ source: 'USER', content: 'Always use short sentences.' }),
      }),
    );
    expect(result.data!.autoGenerated).toBe(false);
    expect(result.data!.promptId).toBe('p-created');
  });

  it('auto-generates when content is omitted', async () => {
    (autoGenerateAndSavePrompt as jest.Mock).mockResolvedValue('Generated content');
    const db = makeDb();
    const ctx = makeCtx(db);
    const result = await tool.handler(ctx, {});
    expect(autoGenerateAndSavePrompt).toHaveBeenCalledWith(
      expect.anything(),
      'org-1',
      ctx.llm.model,
    );
    expect(result.data!.autoGenerated).toBe(true);
  });

  it('auto-generates when content is empty string', async () => {
    (autoGenerateAndSavePrompt as jest.Mock).mockResolvedValue('Generated content');
    const db = makeDb();
    const ctx = makeCtx(db);
    const result = await tool.handler(ctx, { content: '   ' });
    expect(autoGenerateAndSavePrompt).toHaveBeenCalled();
    expect(result.data!.autoGenerated).toBe(true);
  });

  it('emits action_result', async () => {
    const db = makeDb();
    const ctx = makeCtx(db);
    await tool.handler(ctx, { content: 'Explicit prompt.' });
    expect(ctx.emit).toHaveBeenCalledWith(
      expect.objectContaining({ type: 'action_result', ok: true }),
    );
  });

  it('sets label when provided alongside content', async () => {
    const db = makeDb();
    const ctx = makeCtx(db);
    await tool.handler(ctx, { content: 'My prompt.', label: 'Brand voice' });
    expect((db as any).apWritingPrompt.create).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({ label: 'Brand voice' }),
      }),
    );
  });

  it('observation confirms the saved ID', async () => {
    const db = makeDb();
    const ctx = makeCtx(db);
    const result = await tool.handler(ctx, { content: 'Explicit prompt.' });
    expect(result.observation).toContain('p-created');
  });
});
