/**
 * `add_writing_prompt` tool — slice E.8
 *
 * Saves a new writing-instruction prompt for the tenant. If the user does not
 * supply content, triggers `autoGenerateAndSavePrompt` to create one from the
 * business profile. Emits `action_result`.
 *
 * Use when the user says "add a writing prompt", "save this style guide",
 * "create a writing instruction", "generate a writing guide for me".
 */

import { z } from 'zod';
import { PrismaClient } from '@prisma/client';
import type { OrchestratorTool } from '../types';
import { autoGenerateAndSavePrompt } from '../../memory/writing-prompts';

const inputSchema = z.object({
  content: z
    .string()
    .optional()
    .describe(
      'The full text of the writing-instruction prompt. Omit to have the AI auto-generate one from the business profile.',
    ),
  label: z
    .string()
    .optional()
    .describe('Optional human-readable name for this prompt, e.g. "VC voice" or "LinkedIn style".'),
  active: z
    .boolean()
    .optional()
    .describe('Whether the prompt is active (injected into the copywriter). Defaults to true.'),
});

export type AddWritingPromptInput = z.infer<typeof inputSchema>;

export interface AddWritingPromptOutput {
  promptId: string;
  autoGenerated: boolean;
}

export function createAddWritingPromptTool(): OrchestratorTool<
  AddWritingPromptInput,
  AddWritingPromptOutput
> {
  return {
    name: 'add_writing_prompt',
    description:
      'Save a new writing-instruction prompt (style guide) for the account. ' +
      'Supply `content` with the full prompt text, or omit it to have the AI auto-generate one from the business profile. ' +
      'These prompts shape HOW the copywriter writes — not WHAT to post about. ' +
      'Use for "add a writing prompt", "save this style guide", "generate a writing guide for me".',
    parameters: inputSchema,
    handler: async (ctx, input) => {
      const db = ctx.db as unknown as PrismaClient;
      let promptId: string;
      let autoGenerated = false;

      if (!input.content || input.content.trim().length === 0) {
        // Auto-generate from business profile
        const content = await autoGenerateAndSavePrompt(db, ctx.org.id, ctx.llm.model);
        autoGenerated = true;
        const saved = await db.apWritingPrompt.findFirst({
          where: { organizationId: ctx.org.id, content, source: 'AI' },
          orderBy: { createdAt: 'desc' },
        });
        promptId = saved?.id ?? 'unknown';

        if (input.label && saved) {
          await db.apWritingPrompt.update({
            where: { id: saved.id },
            data: { label: input.label },
          });
        }
      } else {
        const created = await db.apWritingPrompt.create({
          data: {
            organizationId: ctx.org.id,
            content: input.content.trim(),
            label: input.label ?? null,
            source: 'USER',
            active: input.active ?? true,
            ordinal: 0,
          },
        });
        promptId = created.id;
      }

      ctx.emit({ type: 'action_result', action: 'add_writing_prompt', ok: true, message: autoGenerated ? `AI-generated writing prompt saved (ID: ${promptId}).` : `Writing prompt saved (ID: ${promptId}).` });
      ctx.logger.info(`add_writing_prompt: org=${ctx.org.id} id=${promptId} autoGenerated=${autoGenerated}`);

      return {
        observation: autoGenerated
          ? `AI-generated writing prompt saved with ID ${promptId}. It will be injected into the copywriter for future content.`
          : `Writing prompt saved with ID ${promptId}. It will be injected into the copywriter for future content.`,
        data: { promptId, autoGenerated },
        emitted: true,
      };
    },
  };
}
