/**
 * `suggest_hashtags` tool — slice E.5
 *
 * Given a piece of content and a target platform, returns a list of relevant
 * hashtags generated by the LLM. Pure read — no stack push, LLM narrates.
 *
 * Use when the user asks "suggest hashtags for this post", "what hashtags
 * should I use?", "give me hashtag ideas for LinkedIn".
 */

import { generateObject } from 'ai-v5';
import { z } from 'zod';
import type { OrchestratorTool } from '../types';

const inputSchema = z.object({
  content: z.string().min(1).describe('The post content to generate hashtags for.'),
  platform: z
    .string()
    .describe('Platform slug (e.g. "twitter", "linkedin", "instagram").'),
  count: z
    .number()
    .int()
    .min(3)
    .max(10)
    .optional()
    .describe('How many hashtags to suggest (3–10). Defaults to 5.'),
});

export type SuggestHashtagsInput = z.infer<typeof inputSchema>;

export interface SuggestHashtagsOutput {
  platform: string;
  hashtags: string[];
}

const outputSchema = z.object({
  hashtags: z
    .array(z.string())
    .describe('Array of hashtag strings including the # prefix (e.g. "#marketing").'),
});

export function createSuggestHashtagsTool(): OrchestratorTool<
  SuggestHashtagsInput,
  SuggestHashtagsOutput
> {
  return {
    name: 'suggest_hashtags',
    description:
      'Generate relevant hashtag suggestions for a post on a given platform. Use when the user asks "suggest hashtags", "what hashtags should I use?", "hashtag ideas". Returns a list — does NOT push anything to the draft queue.',
    parameters: inputSchema,
    handler: async (ctx, input) => {
      const count = input.count ?? 5;

      const { object } = await generateObject({
        model: ctx.llm.model,
        schema: outputSchema,
        prompt: [
          `Generate exactly ${count} relevant hashtags for the following ${input.platform} post.`,
          `Each hashtag must start with "#", be lowercase, no spaces.`,
          `Focus on relevance, discoverability, and niche fit.`,
          ``,
          `Post content:`,
          input.content,
        ].join('\n'),
      });

      const hashtags = object.hashtags.slice(0, count);
      const observation = `Suggested ${hashtags.length} hashtag(s) for ${input.platform}: ${hashtags.join(', ')}`;

      ctx.logger.info(
        `suggest_hashtags: org=${ctx.org.id} platform=${input.platform} count=${hashtags.length}`,
      );

      return {
        observation,
        data: { platform: input.platform, hashtags },
      };
    },
  };
}
